### ISSUE TITLE
Couple questions/suggestions

### ISSUE THREAD

**Issue by vladar** [vasily-kartashov/graphql-batch-processing#1]
Hey, nice and simple library!

One thing is a bit confusing though: `Batch::as('key')` - it is not quite obvious why do we need this key in the first place? I couldn't find any usages of this key in the code (apart from array storage key).

Could it be just `Batch::create($key = null)` (with an optional key, so that it could be generated by the library if omitted).

Or am I missing something?

**Comment by vasily-kartashov** [comment]
Batch key is a pretty much the namespace for cached values. You can see it this way: batch key + "collected ID" gives a unique cache ID. And we want to keep the "collected ID" free from namespaces, because this is what we use to unwrap the repository response. 

Typical repository method would look like this
```
public function findUsersByUserIds(array $userIds) {
    $query = '
        SELECT * FROM users WHERE id IN ?
    ';
    ...
}
```
and return an assoc array pointing from user ID to user entity.
